import Link from 'next/link';
import { notFound } from 'next/navigation';
import { projects } from '@/data/projects';
import { Photo, PageIntro, Breadcrumbs, JsonLd } from '@/components/editorial';
import { pageMetadata } from '@/lib/seo';
import { site } from '@/config/site';
export function generateStaticParams(){return projects.map(p=>({slug:p.slug}));}
export async function generateMetadata({params}:{params:Promise<{slug:string}>}){const {slug}=await params;const p=projects.find(p=>p.slug===slug);return p?pageMetadata(p.title,`/projects/${p.slug}/`,p.description):{};}
function Content({title,text}:{title:string;text:string}){return <section className="project-story"><h2>{title}</h2><p className={text?'':'muted'}>{text||'Project content placeholder — awaiting verified studio documentation.'}</p></section>;}
function Gallery({title,images}:{title:string;images:string[]}){return <section className="project-story"><h2>{title}</h2>{images.length?<div className="detail-gallery">{images.map((src,i)=><Photo key={src} src={src} alt={`${title} for project, image ${i+1}`}/>)}</div>:<p className="pending-panel">{title} placeholder — approved project images will be added here.</p>}</section>;}
export default async function ProjectDetail({params}:{params:Promise<{slug:string}>}){const {slug}=await params;const p=projects.find(p=>p.slug===slug);if(!p)notFound();return <><Breadcrumbs title={p.title} path={`/projects/${p.slug}/`}/><PageIntro eyebrow={p.placeholder?'Project placeholder':'Project story'} title={p.title}/><div className="wrap"><Photo className="wide-photo" src={p.coverImage} alt={p.placeholder?`Stock interior reference for ${p.title}; not CraftedByDuna work`:`${p.title} project`} priority/>{p.placeholder&&<p className="placeholder-banner">Editable project placeholder. Stock photography is a visual reference and does not depict CraftedByDuna work. Project facts remain unconfirmed.</p>}<dl className="project-facts">{[['Location',p.location||'To be confirmed'],['Year',p.year?.toString()||'To be confirmed'],['Category',p.category.join(' / ')||'To be confirmed'],['Scope',p.scope.join(' / ')||'To be confirmed'],['Status',p.status]].map(([k,v])=><div key={k}><dt>{k}</dt><dd>{v}</dd></div>)}</dl><Content title="Project overview" text={p.description}/><Content title="Client challenge" text={p.challenge}/><Content title="Design approach" text={p.solution}/><Content title="Design decisions" text={p.decisions.join(' · ')}/><Content title="Materials" text={p.materials.join(' · ')}/><Gallery title="Drawings / render" images={p.drawings}/><Gallery title="Construction progress" images={p.processImages}/><div className="comparison-grid"><Gallery title="Before" images={p.beforeImages}/><Gallery title="After" images={p.afterImages}/></div><Gallery title="Final gallery" images={p.gallery}/><section className="similar-project"><h2>Have a similar project?</h2><p>Let’s discuss your space, priorities, and possibilities.</p><Link className="button dark" href="/contact/">Start a Project</Link></section></div>{!p.placeholder&&<JsonLd data={{'@context':'https://schema.org','@type':'CreativeWork',name:p.title,description:p.description,url:site.url+`/projects/${p.slug}/`,creator:{'@id':site.url+'/#organization'},image:site.url+p.coverImage}}/>}</>;}
