'use client';
import { useState, type FormEvent } from 'react';
import { site, whatsappUrl } from '@/config/site';
export default function InquiryForm() {
 const [status,setStatus]=useState(''); const [busy,setBusy]=useState(false); const [draft,setDraft]=useState('');
 async function submit(e:FormEvent<HTMLFormElement>) { e.preventDefault(); const form=e.currentTarget; if(!form.reportValidity())return; const data=new FormData(form); const message=`Hi CraftedByDuna, I would like to discuss a project.\n\n${Array.from(data.entries()).filter(([k])=>k!=='consent').map(([k,v])=>`${k}: ${v}`).join('\n')}`; setDraft(message);
 if(site.formEndpoint) { setBusy(true); setStatus('Sending your inquiry…'); try { const response=await fetch(site.formEndpoint,{method:'POST',body:data,headers:{Accept:'application/json'}}); if(!response.ok)throw new Error('Submission failed'); setStatus('Thank you. Your inquiry has been sent.'); setDraft(''); form.reset(); } catch { setStatus('Your inquiry could not be sent. Your details remain here. Please retry or use the WhatsApp / copy option below.'); } finally { setBusy(false); } }
 else setStatus(site.whatsapp?'Your inquiry is ready. Continue on WhatsApp to send it; it has not been sent yet.':'Contact setup is pending. Your inquiry is ready to copy, but has not been sent or saved to a server.');
 }
 return <form className="inquiry-form" onSubmit={submit}><div className="form-grid"><label>Full Name<input name="Full name" autoComplete="name" required maxLength={120}/></label><label>WhatsApp<input name="WhatsApp" type="tel" autoComplete="tel" required pattern="[+0-9() .-]{7,25}" title="Enter a phone number with 7–25 characters."/></label><label>Email<input name="Email" type="email" autoComplete="email" required maxLength={254}/></label><label>Project Location<input name="Project location" required maxLength={200} placeholder="City / neighbourhood"/></label><label>Project Type<select name="Project type" required defaultValue=""><option value="" disabled>Select project type</option><option>Residential</option><option>Commercial / Ruko</option><option>Other</option></select></label><label>Service<select name="Service" required defaultValue=""><option value="" disabled>Select service</option><option>Interior</option><option>Architecture</option><option>Build</option><option>Interior + Architecture + Build</option></select></label></div><label>Estimated Project Timeline<input name="Timeline" required maxLength={200} placeholder="e.g. early next year, or still exploring"/></label><label>Message / Project Description<textarea name="Project description" rows={5} required minLength={10} maxLength={4000} placeholder="Tell us about the space and what you have in mind."/></label><label className="consent"><input name="consent" type="checkbox" required value="agreed"/>I agree to be contacted regarding this project.</label><p className="muted">Your details are used to respond to this inquiry. {site.formEndpoint?'Submitting sends them to our configured inquiry service.':'This form prepares a message; it does not store your details.'}</p><button className="button dark" disabled={busy}>{busy?'Sending…':'Send Project Inquiry'}</button><p role="status" className="form-status">{status}</p>{draft && <div className="inquiry-draft"><label>Your prepared inquiry<textarea readOnly rows={8} value={draft}/></label><div className="button-row">{site.whatsapp&&<a className="button dark" href={whatsappUrl(draft)} target="_blank" rel="noopener noreferrer">Continue on WhatsApp</a>}<button type="button" className="button outline" onClick={async()=>{try {await navigator.clipboard.writeText(draft);setStatus('Inquiry copied. Send it using the contact channel once available.');}catch{setStatus('Select and copy the message above.');}}}>Copy inquiry</button></div></div>}</form>;
}
